version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-10-23T03-28-24Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - minio_data1_1:/data1
      - minio_data1_2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - minio_data2_1:/data1
      - minio_data2_2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - minio_data3_1:/data1
      - minio_data3_2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - minio_data4_1:/data1
      - minio_data4_2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## This config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio_data1-1:
    driver: local
  minio_data1-2:
    driver: local
  minio_data2-1:
    driver: local
  minio_data2-2:
    driver: local
  minio_data3-1:
    driver: local
  minio_data3-2:
    driver: local
  minio_data4-1:
    driver: local
  minio_data4-2:
    driver: local
